### ISSUE TITLE
Tons of kinda minor issues

### ISSUE THREAD

**Issue by DragonSlayer2189** [TotalFreedomMC/TotalFreedomMod#259]
anyways heres some more minor things that still need to be done, the main reason why most of these haven't been done is due to requireing FTP acess which only @Seth  has :
 - link in /mbi needs to be changed to https://totalfreedom.boards.net/thread/65477/master-builder-application-template-2019 (this can be done in config.yml of TFM)

- essentials rules.txt needs to be updated to the current conduct policy

- Idk why but /playtime is blocked for ops, i dont think it need to be

- despite the fact that in code it says senior admins should be able to do /curse, they in fact, can not

- items.json needs to be regenerated

- "pinger" setting in bungee for smp/freeop needs to be set to true

- in bungee config, it needs to be changed so that you always start in freeop, i have seen new players try to join freeop, but they end up going to smp for some reason, think theres nothing else there, and then leave

- /stopsound just flat out doesnt work as in, it doesnt stop any sounds

- even when theres an invalid item insted of just stopping, if you do "/dispfill 3(or any radius) test" insted of just saying invalid item, it will say that it skips that item and then will try to fill the dispensers anyways

- /blockedit allows you to set a reason but the reason is never seen or used in any way

- /mp44 has been disabled for so long, we should either remove it or fix it

- /premium is no longer neccissary to even have, but whatever

- /reactionbar will force a reaction to happen this can be started by any senior admin dev, sounds to me like something that would be pretty easy to abuse, however i can't test this atm

- what is even the point of /setlever

- /tagnyan and /tagrainbow are redundant and can be murged as a subcommand of /tag

- /tban allows you to set a reason however the reason is never shown to anybody, also -q does not work with it

- links from https://totalfreedom.boards.net/thread/66391/important-admin-links-electric-boogaloo should mabye be added to /links per this suggestion: https://totalfreedom.boards.net/thread/67843/httpd-resources-command

- when using /smite <player> [reason] -q it displays a "Smitten [player] quietly." message, this would be nice to have on other commands that have the silent flag, mabye also send a message like "[player] has been [type of punishment]ed silently." to all admins

- please fix /tossmob it sounds so fucking cool, make it a shop item or something i dont care

- version part of /tfm always has this bit that says "Unknown" idk if this is a bug, but it is annoying to me
[https://cdn.discordapp.com/attachments/727428136815296652/740371042496806962/unknown.png](url)

- why do we need a /whitelist command, that is already supplied by mojang themselves i believe

- silent flag (-q) doesn't work inside of /warn, which honestly is something that would be super usefull if you were in vanish or something

- seems weird to me that we can wipe all the punishment log for a specific player, that sounds like something that could lead to abuse

- in /mute, the -q or -s comes before the reason rather than after, like every single other command, this should be fixed for consistansy

telesephero told me to make this, dont @ me

**Comment by DragonSlayer2189** [comment]
also /potion doesn't work for ops, it thinks that your trying to execute it on another player

**Comment by ghost** [comment]
/tossmob seems to only be toggleable by editing the config, unsure if it works or not

/warn doesn't have a -q arg, same with /tban

agree on /setlever - what even is the point of it lol 

/links as I already said are for tf social media links

**Comment by VideoGameSmash12** [comment]
you tagged the wrong seth

**Comment by ncurran02** [comment]
> you tagged the wrong seth

This was copied from the thread on the forum.

**Comment by ncurran02** [comment]
- `/mp44` is configurable however the feature is not implemented (looks like it got removed).
- `/curse` is an executive-only command.
- `/reactionbar` is intentional but only for developers (testing purposes).
- `/tagnyan` and `/tagrainbow` are still useful - if we remove then we should remove like 80% of the commands and plugins.
- `/tossmob` is configurable but can't be toggled in-game.
- Wiping all punishments is a senior-only command so if someone did abuse the command, someone would know.
- /tfm unknown part occurs when someone compiles it but doesn't configure their maven properties properly but it's not a huge deal as Seth is the only one who compiles the server branch for the main server.

**Comment by ghost** [comment]
/blockedit has a -s argument meaning you can block edits for a player, and smite them with a reason

**Comment by DragonSlayer2189** [comment]
> * `/tagnyan` and `/tagrainbow` are still useful - if we remove then we should remove like 80% of the commands and plugins.

nah, not suggesting that we remove it, but that we move it to be part of /tag, similar to how /tag gradient is not its own command, but just part of /tag

**Comment by ncurran02** [comment]
> > * `/tagnyan` and `/tagrainbow` are still useful - if we remove then we should remove like 80% of the commands and plugins.
> 
> nah, not suggesting that we remove it, but that we move it to be part of /tag, similar to how /tag gradient is not its own command, but just part of /tag

Yeah, I misread it.

**Comment by XenVoltz** [comment]
Since this issue to for minor issues, I'll post this here. 

https://gyazo.com/3e52a492627543e812e111f42e6d51a8

Should say /list -s or /who -s

**Comment by script-head** [comment]
link in /mbi needs to be changed to https://totalfreedom.boards.net/thread/65477/master-builder-application-template-2019 (this can be done in config.yml of TFM) - **unrelated to the core development as the actual server config values on the server are different from here**

essentials rules.txt needs to be updated to the current conduct policy
 **this isnt even tfm related**

Idk why but /playtime is blocked for ops, i dont think it need to be
**there is no system for tracking activity from ops.**

despite the fact that in code it says senior admins should be able to do /curse, they in fact, can not
**removing the command because the texture back is gone**

items.json needs to be regenerated
**again, not TFM related, but i did it anyway**

"pinger" setting in bungee for smp/freeop needs to be set to true
**not a tfm issue**

in bungee config, it needs to be changed so that you always start in freeop, i have seen new players try to join freeop, but they end up going to smp for some reason, think theres nothing else there, and then leave
**not tfm related**

/stopsound just flat out doesnt work as in, it doesnt stop any sounds
**ill look into it**

even when theres an invalid item insted of just stopping, if you do "/dispfill 3(or any radius) test" insted of just saying invalid item, it will say that it skips that item and then will try to fill the dispensers anyways
*will look into it**

/blockedit allows you to set a reason but the reason is never seen or used in any way
**will fix it**

/mp44 has been disabled for so long, we should either remove it or fix it
**ill make it a shop item**

/premium is no longer neccissary to even have, but whatever
**whatever**

/reactionbar will force a reaction to happen this can be started by any senior admin dev, sounds to me like something that would be pretty easy to abuse, however i can't test this atm
**if my devs become abusive report them and ill remove them.**

what is even the point of /setlever
**to set a lever at a specified block position**

/tagnyan and /tagrainbow are redundant and can be murged as a subcommand of /tag
**@TFPatches/developers im too lazy to merge them**

tban allows you to set a reason however the reason is never shown to anybody, also -q does not work with it
**will fix it**

links from https://totalfreedom.boards.net/thread/66391/important-admin-links-electric-boogaloo should mabye be added to /links per this suggestion: https://totalfreedom.boards.net/thread/67843/httpd-resources-command
**admins can find the list from a forum thread, if one doesnt exist, make it.**

when using /smite [reason] -q it displays a "Smitten [player] quietly." message, this would be nice to have on other commands that have the silent flag, mabye also send a message like "[player] has been [type of punishment]ed silently." to all admins 
**@TFPatches/developers im lazy one of u do this**

please fix /tossmob it sounds so fucking cool, make it a shop item or something i dont care
**will be a shop item**

version part of /tfm always has this bit that says "Unknown" idk if this is a bug, but it is annoying to me
    https://cdn.discordapp.com/attachments/727428136815296652/740371042496806962/unknown.png
**git scm take is fucked in the pom somewhere**

why do we need a /whitelist command, that is already supplied by mojang themselves i believe
**we added an addall function**

silent flag (-q) doesn't work inside of /warn, which honestly is something that would be super usefull if you were in vanish or something
**ok ill fix it**

seems weird to me that we can wipe all the punishment log for a specific player, that sounds like something that could lead to abuse 
**if its abused r e p o r t   i t**

in /mute, the -q or -s comes before the reason rather than after, like every single other command, this should be fixed for consistansy
**ill fix it**

**Comment by Telesphoreo** [comment]
Many of the issues in here have been fixed.

The only one I can comment on right now is merging tagrainbow and tagnyan into tag and personally I don't think we should. The tag command is already a mouthful and it's good that it's deconstructed.

The -q flag has been added for more commands if I recall but I'll do it if it isn't already

**Comment by berwil-1** [comment]
> also /potion doesn't work for ops, it thinks that your trying to execute it on another player

Fixed
